// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void open_terminal_btn(lv_event_t * e)
{
	// Your code here
}

void check_key_btn(lv_event_t * e)
{
	// Your code here
}
